- name: configuring backend
  hosts: backend
  become: yes
  tasks:
  - name: disable nodejs 16
    ansible.builtin.command: " dnf module disable nodejs -y "

  - name: enable nodejs 20
    ansible.builtin.command: " dnf module enable nodejs:20 -y "

  - name: install nodejs 20
    ansible.builtin.dnf:
      name: nodejs
      state: installed

  - name: create expense user
    ansible.builtin.user:
      name: expense

  - name: create a directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: download backend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: unzip backend code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy backend service
    ansible.builtin.copy:
      src: backend.service
      dest: /etc/systemd/system/backend.service

  - name: import mysql data
    community.mysql.mysql_db:
      state: import
      name: all
      login_user: root
      login_password: ExpenseApp@1
      login_host: 172.31.42.65
      target: /app/schema/backend.sql

  - name: daemon reload and start backend
    ansible.builtin.systemd.service:
      enabled: true
      state:  restarted
      daemon-reload: true
      name: backend
      

