- name: install mysql
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: enable services
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login-password: ExpenseApp@1
      login_host: 172.31.42.65
    register: mysql_info
    ignore_errors: true
    